### PR TITLE
Add Swift Package Manager support

### PR DESCRIPTION
**Pull request by Ded77**
cf. https://github.com/mParticle/mparticle-apple-sdk/issues/125

### CODE REVIEW

**Comment by samdozor** [comment]
@Ded77 thank you for the PR! I've assigned @peterjenkins to review it.

**Comment by Ded77** [comment]
@peterjenkins It should be fixed :)

**Comment by Ded77** [comment]
Hi @peterjenkins ! Any news about my PR ? Is it ok or should I change something ?
Thank you :)

**Comment by majcher33** [comment]
@peterjenkins Does that mean the mparticle team will handle updating the other kits to support SPM? I was planning on submitting pull requests for a few, but I will wait if it's on the roadmap.

**Pull request merged**
